// Code generated by gentmpl. DO NOT EDIT.
package tmpl

var Templates = map[string]string{
	"bash": `#!/bin/bash
# {{benchmark.Title}}
# Version: {{benchmark.Version}} {{benchmark.ReleaseInfo}}
{{$STIG := replace .Id "-" "_" -1 -}}
{{$STIG}} () {

STIG_ID={{.Id}}
STIG_SEVERITY={{(index .Rules 0).SeverityAttr}}
STIG_DESCRIPTION () {
  cat <<'STIG_END'
Group Id: {{.Id}}
Group Title: {{.Title}}
{{- range .Rules}}
Rule Id: {{.Id}}
Rule Severity: {{.Severity}}
Rule Version: {{.Version}}
{{printf "Rule Title: %s" .Title | wrap}}

Discussion:
{{wrap .Description.Discussion}}

Check Content:
{{wrap .CheckContent}}

Fix Text:
{{wrap .FixText}}
{{- end}}
STIG_END
}

# Apply STIG changes
# Return 0=OK, 1=FAIL, 2=NOT IMPLEMENTED
apply () {
  return 2 # NOT IMPLEMENTED
}

# Revert STIG changes
# Return 0=OK, 1=FAIL, 2=NOT IMPLEMENTED
revert () {
  return 2 # NOT IMPLEMENTED
}

# Check STIG compliance
# Return 0=OK, 1=FAIL, 2=NOT IMPLEMENTED
status () {
  return 2 # NOT IMPLEMENTED
}

} # END OF {{$STIG}}
STIG_ITEMS+=({{$STIG}})

if [ "$(basename "${0#-}")" = {{.Id}}.sh ]; then
  STIG_DIR=$(cd "$(dirname "$0")"; pwd)
  source "${STIG_DIR}"/common.sh
  main "$@"
fi
`,
}
